export const CHATBOT_KNOWLEDGE = [
  {
    key: 'diversification',
    aliases: ['diversify', 'diversified portfolio', 'sector diversification', 'diversification'],
    simple: 'Diversification means spreading simulated capital across multiple stocks and sectors.',
    detailed: 'It helps reduce concentration risk because one stock or sector does not dominate the whole portfolio.',
    example: 'Holding five technology stocks may not be truly diversified if all react to the same technology news.',
    relatedLessonIds: ['diversification-risk', 'portfolio-risk'],
    relatedQuizIds: ['portfolio-risk-quiz'],
    warning: 'Diversification reduces some risks but does not guarantee profit.',
  },
  {
    key: 'volatility',
    aliases: ['volatility', 'volatile', 'price swing'],
    simple: 'Volatility describes how widely and quickly a simulated price moves.',
    detailed: 'Higher volatility can create larger gains and larger losses, so position sizing matters.',
    example: 'A stock like SLRX may move more sharply than a lower-volatility stock in the simulation.',
    relatedLessonIds: ['risk-return', 'risk-management'],
    relatedQuizIds: ['risk-management-quiz'],
    warning: 'High volatility does not mean guaranteed opportunity.',
  },
  {
    key: 'stop-loss',
    aliases: ['stop loss', 'stop-loss', 'stoploss'],
    simple: 'A stop-loss is a simulated order that can trigger an exit when price falls to a set level.',
    detailed: 'It helps learners plan risk before emotions appear, but it does not remove risk.',
    example: 'In the simulator, you can practice a sell stop-loss below your entry to study drawdown control.',
    relatedLessonIds: ['order-types', 'risk-management'],
    relatedQuizIds: ['risk-management-quiz'],
    warning: 'A stop-loss is a practice tool here, not a real-market guarantee.',
  },
  {
    key: 'bid ask spread',
    aliases: ['bid ask', 'spread', 'bid', 'ask'],
    simple: 'The spread is the difference between the bid price and the ask price.',
    detailed: 'The bid is what buyers are willing to pay; the ask is what sellers want to receive.',
    example: 'A wider spread can explain why execution price differs from the displayed last price.',
    relatedLessonIds: ['market-basics', 'order-types'],
    relatedQuizIds: ['basics-quiz'],
  },
  {
    key: 'drawdown',
    aliases: ['drawdown', 'downside', 'loss from high'],
    simple: 'Drawdown measures how far a simulated portfolio falls from a previous high.',
    detailed: 'Large drawdowns can be difficult to recover from and are useful for risk review.',
    example: 'A fall from 150,000 to 135,000 is a 10% drawdown.',
    relatedLessonIds: ['risk-return', 'risk-management', 'portfolio-risk'],
    relatedQuizIds: ['risk-management-quiz'],
  },
  {
    key: 'rsi',
    aliases: ['rsi', 'relative strength index', 'overbought', 'oversold'],
    simple: 'RSI is a momentum indicator that ranges from 0 to 100.',
    detailed: 'Above 70 can suggest overbought conditions, while below 30 can suggest oversold conditions.',
    example: 'Use RSI in Market Lab as one signal, not as a standalone decision rule.',
    relatedLessonIds: ['technical-indicators'],
    relatedQuizIds: ['technical-quiz'],
  },
  {
    key: 'macd',
    aliases: ['macd', 'signal line', 'momentum indicator'],
    simple: 'MACD compares short and long moving averages to show momentum changes.',
    detailed: 'A MACD line above the signal line can indicate bullish momentum in the simulation.',
    example: 'Market Lab plots MACD and signal lines for practice.',
    relatedLessonIds: ['technical-indicators'],
    relatedQuizIds: ['technical-quiz'],
  },
  {
    key: 'bollinger bands',
    aliases: ['bollinger', 'bollinger bands', 'bands'],
    simple: 'Bollinger Bands show a price envelope around a moving average.',
    detailed: 'They help learners see whether a price is near the upper or lower part of its recent range.',
    example: 'A price near the upper band may be extended, but confirmation is still needed.',
    relatedLessonIds: ['technical-indicators'],
    relatedQuizIds: ['technical-quiz'],
  },
  {
    key: 'market order',
    aliases: ['market order', 'market buy', 'market sell'],
    simple: 'A market order prioritizes immediate simulated execution.',
    detailed: 'It can fill quickly but does not provide exact price control.',
    example: 'Use it in the simulator when learning how cash and holdings change immediately.',
    relatedLessonIds: ['order-types'],
    relatedQuizIds: ['basics-quiz'],
  },
  {
    key: 'limit order',
    aliases: ['limit order', 'limit buy', 'limit sell'],
    simple: 'A limit order sets the maximum buy price or minimum sell price you accept.',
    detailed: 'It gives price control but may not execute if the simulated market does not reach the limit.',
    example: 'A limit buy at 95 only executes if price reaches 95 or lower.',
    relatedLessonIds: ['order-types'],
    relatedQuizIds: ['basics-quiz'],
  },
  {
    key: 'portfolio',
    aliases: ['portfolio', 'holdings', 'cash', 'market value', 'unrealized p/l', 'realized p/l'],
    simple: 'A portfolio is your simulated cash plus stock holdings.',
    detailed: 'It shows active positions, average price, market value, allocation, and profit/loss.',
    example: 'If you hold 10 shares at a current price of 50, that holding has a market value of 500.',
    relatedLessonIds: ['portfolio-basics'],
    relatedQuizIds: ['portfolio-risk-quiz'],
  },
  {
    key: 'news impact',
    aliases: ['news', 'headline', 'sentiment', 'market sentiment', 'sector news'],
    simple: 'News can change simulated demand by shifting optimism or fear.',
    detailed: 'Company news may affect one ticker; sector-wide or macro news can affect many tickers.',
    example: 'Positive energy news may affect several Energy tickers, not only one company.',
    relatedLessonIds: ['news-impact', 'market-sentiment'],
    relatedQuizIds: ['news-impact-quiz'],
  },
  {
    key: 'trading psychology',
    aliases: ['fomo', 'panic selling', 'overtrading', 'confirmation bias', 'loss aversion', 'revenge trading', 'journal'],
    simple: 'Trading psychology is how emotions and habits affect simulated decisions.',
    detailed: 'FOMO, overtrading, confirmation bias, and revenge trading can lead to poorly planned trades.',
    example: 'A trading journal records reason, risk, result, and lesson learned.',
    relatedLessonIds: ['investment-psychology', 'trading-psychology'],
    relatedQuizIds: ['investment-psychology-quiz'],
  },
  {
    key: 'fundamental analysis',
    aliases: ['fundamental', 'revenue', 'profit', 'financial health', 'investment thesis', 'risk factors', 'consultant note'],
    simple: 'Fundamental analysis studies the business, evidence, thesis, and risk factors.',
    detailed: 'In SoictStock it is used for simulation-only company analysis, not real investment advice.',
    example: 'A good note explains opportunity and risk instead of only giving an action label.',
    relatedLessonIds: ['fundamental-analysis', 'consultant-analysis'],
    relatedQuizIds: ['advisory-thinking-quiz'],
  },
];

export function findKnowledgeItem(message = '') {
  const text = message.toLowerCase();
  return CHATBOT_KNOWLEDGE.find((item) => item.aliases.some((alias) => text.includes(alias)));
}
