export const CONSULTANTS = [
  {
    id: 'financial-education',
    name: 'Financial Education Consultant',
    role: 'Learning Guide',
    expertise: ['market basics', 'orders', 'learning path'],
    description: 'Helps new users understand stock market fundamentals and simulation features.',
    bestFor: ['new users', 'basic concepts', 'learning path'],
    relatedIntents: ['ExplainConcept', 'RecommendLesson', 'PlatformHelp'],
    icon: 'EDU',
    bookingLabel: 'Book education session',
  },
  {
    id: 'portfolio-consultant',
    name: 'Portfolio Consultant',
    role: 'Portfolio Strategy Guide',
    expertise: ['allocation', 'diversification', 'portfolio construction'],
    description: 'Helps users understand portfolio structure and diversification in the simulation.',
    bestFor: ['portfolio review', 'diversification', 'allocation'],
    relatedIntents: ['ExplainPortfolio', 'RiskAnalysis'],
    icon: 'PF',
    bookingLabel: 'Book portfolio review',
  },
  {
    id: 'risk-management',
    name: 'Risk Management Analyst',
    role: 'Risk Coach',
    expertise: ['volatility', 'drawdown', 'stop-loss', 'position sizing'],
    description: 'Helps users practice risk control and simulated trading discipline.',
    bestFor: ['high-risk portfolios', 'drawdown', 'position sizing'],
    relatedIntents: ['RiskAnalysis', 'TradeFeedback', 'OrderHelp'],
    icon: 'RM',
    bookingLabel: 'Book risk session',
  },
  {
    id: 'equity-research',
    name: 'Equity Research Analyst',
    role: 'Stock Analysis Guide',
    expertise: ['fundamental analysis', 'investment thesis', 'risk factors'],
    description: 'Helps users structure simulation-only company analysis.',
    bestFor: ['stock analysis', 'thesis writing', 'risk factors'],
    relatedIntents: ['ExplainStockMovement', 'NewsExplanation'],
    icon: 'ER',
    bookingLabel: 'Book stock analysis session',
  },
  {
    id: 'technical-analysis',
    name: 'Technical Analysis Specialist',
    role: 'Chart Learning Guide',
    expertise: ['RSI', 'MACD', 'moving averages', 'candlesticks'],
    description: 'Helps users understand technical indicators and chart patterns.',
    bestFor: ['technical indicators', 'candlestick patterns', 'market lab'],
    relatedIntents: ['ExplainConcept', 'PlatformHelp'],
    icon: 'TA',
    bookingLabel: 'Book technical review',
  },
];
